# Generated by Django 5.2.6 on 2026-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('liturgico', 'Litúrgico'), ('feriado', 'Feriado'), ('personalizado', 'Personalizado')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
